### ISSUE TITLE
Include un-minified VaadinGridImport.nocache.js

### ISSUE THREAD

**Issue by jhawlwut** [vaadin/vaadin-grid#101]
While digging through the build, I noticed that there's no easy way to modify the javascript that actually renders the grid component because the file, VaadinGridImport.nocache.js, appears to be minified. I understand the option to build from source using this repository, but if you're marketing this as a "drag-and-drop" web component for HTML5/Javascript, can the build at least include an un-minified file that allows the developer to minify after they've modified?

**Comment by jounik** [comment]
Hi @jhawlwut!

Sorry for being late with the reply, I completely forgot!

As for `VaadinGridImport.nocache.js`, it’s actually generated JavaScript, compiled by from the GWT source code for the grid. `v-grid` is actually a Web Component wrapper for the Vaadin Framework Grid component (see https://vaadin.com/grid), and the original implementation is written in Java.

So you should never modify the compiled JS code. You can generate a human readable version of the file if you want to, though. There are instructions in the readme how to set up the project and how to compile it.

I’m not sure if it would be helpful to include the unobfuscated version of the compiled JS in the release package. Perhaps for debugging, but since you can’t do the fix in the JS code, I don’t really see the point.

**Comment by jounik** [comment]
Closing, since I don’t think we will ever publish the unobfuscated JS, it really doesn’t serve the users. It might just give the wrong idea that it can be directly modified.

If you wish to debug the generated JS, you can use the "pretty" output option described in the readme: https://github.com/vaadin/vaadin-grid#development-protips

**Comment by ktiedt** [comment]
I have to disagree with this logic... 

1) unobfuscated code does not promote 'editing the file directly' - it does however promote troubleshooting and opening more detailed bug reports, or pull requests to fix the bug because they were able to quickly and easily delve into the code and with minimal effort, find and fix it.

2) It also allows for developers to work the compressing into their workflow which may include extern and or SourceMap generation to aide in their development process.

Please don't limit your users ability to help themselves AND your team in making vaadin-grid even better.

**Comment by Saulis** [comment]
Here's the `<vaadin-grid>` 0.9.0-beta5 compiled with pretty (ugly) formatting:
https://gist.github.com/Saulis/2037bcebfe217251df62

If someone finds this helpful in any way, we might reconsider including it in our packaging.

**Comment by ktiedt** [comment]
Yeah, Marcus showed me this yesterday, the fact that this is generated from
GWT didnt really register initially. The 'pretty' code is almost as bad as
the minified code :(

-Karl Tiedt

**Comment by vbolshutkin** [comment]
While trying to make vaadin grid work under Ionic 2 application I encountered very strange issue only in FF.  So, I would find helpful if human-readable version was available at cdn near https://cdn.vaadin.com/vaadin-core-elements/latest/vaadin-grid/vaadin-grid.min.js . 

Using the gist above I was able to match a bit outdated unminified code with latest minified and find a workaround. But to understand the initial cause and fix it I will definitely need a latest human-readable version.

**Comment by vbolshutkin** [comment]
Tried to build my own according to instructions, but Maven 3.3.3 failed to resolve dependencies (at both `master` branch and `v1.2.1` tag).
```
[ERROR] Failed to execute goal on project vaadin-grid: Could not resolve dependencies for project com.vaadin.elements:vaadin-grid:war:1.2.0: Failed to collect dependencies at com.vaadin:vaadin-widgets:jar:7.7.0.elements3: Failed to read artifact descriptor for com.vaadin:vaadin-widgets:jar:7.7.0.elements3: Failure to find com.vaadin:vaadin-root:pom:7.7.0-SNAPSHOT in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

**Comment by manolo** [comment]
For some reason there is a dependency missing in maven repos.
In the meanwhile we fix the issue, you can change `<vaadin.version>7.7.0.elements3</vaadin.version>` by `<vaadin.version>7.7.0.elements2</vaadin.version>` in java/pom.xml

**Comment by platosha** [comment]
@vbolshutkin I would recommend you to try upgrading to grid 2.0 already. It was completely rewritten in JavaScript, should be a bit easier to debug.

The latest release is `v2.0.0-alpha4`. No need to upgrade Polymer, we are still using Polymer v1.x in `<vaadin-grid>` v2.0. See this wiki page for the API changes: https://github.com/vaadin/vaadin-grid/wiki/Migration-from-1.*-to-2.0
