### ISSUE TITLE
Text selection buggy

### ISSUE THREAD

**Issue by nikove** [vaadin/vaadin-grid#1022]
The selection of text in the grid seems to be a little buggy at the moment:
https://vaadin.com/elements/vaadin-grid/html-examples/grid-basic-demos

If I select text across multiple cells e.g. from bottom right to top left, only some of the text is selected. Quite often an entire column worth of text is unselected, making it look quite strange.

![selecting text in a grid](https://user-images.githubusercontent.com/29984911/31058287-1c0df050-a6a6-11e7-9cbf-e567133de339.jpg)

**Comment by jouni** [comment]
Noticed this one also last week.

**Comment by tomivirkki** [comment]
Native text selection (+ copy pasting to sheets etc) might be impossible to be made working properly on all supported browsers since we modify the internal table display a lot and the scrolling is virtual so you’re never actually selecting more than a few visible rows. We should probably consider virtual selection+copying.

**Comment by platosha** [comment]
There was an issue in the demo causing this, fixed already. The fix was included v4.0.0-alpha4.

The website demo is updated as well.
