### ISSUE TITLE
'selected" is not updating for me

### ISSUE THREAD

**Issue by chisholmd** [vaadin/vaadin-grid#1045]
<vaadin-grid-column resizable>
        <template class="header">
            Some column head
        </template>
        <template>

          {{selected}}
 
        </template>
      </vaadin-grid-column>

When first loaded {{selected}} will show correct value "false"  but selecting rows does not update the value.  They continue to say false

The demo is not working so I can't tell if its just me or not.
https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/selection.html

**Comment by chisholmd** [comment]
In vaadin-grid-selection-behavior.html  the _isSelected function only checks the selectedItems array. So if multi select is not turned on, it always returned false.  I think _isSelected also needs to check this.activeItem==item

    _isSelected: function(item) {
      return this.selectedItems && this.selectedItems.indexOf(item) > -1;
    },

**Comment by platosha** [comment]
Adding a check for `activeItem` in `_isSelected(item)` might result in a mismatch between `selectedItems[]` contents and the items that are displayed as selected in the grid. We don’t want to introduce such a mismatch.

If you would like to display `activeItem` as selected, you can add `activeItem` to the `selectedItems` array, as shown on the selection demo. Changes to `selectedItems` array should trigger `{{selected}}` column template variable.

Note that due to JavaScript design, Polymer can not easily detect array mutations. To workaround that, when changing `selectedItems` array, either replace it with a new array instance:

```javascript
grid.selectedItems = [activeItem];
```

... or use Polymer array mutation methods:

```javascript
grid.splice('selectedItems', 0, 1, selectedItem);
```

Also, try a demo from the recent alpha. Does this demo work for you?
https://cdn.vaadin.com/vaadin-grid/4.0.0-alpha5/demo/#grid-selection-demos
