### ISSUE TITLE
Setting a renderer with a column attribute

### ISSUE THREAD

**Issue by cbwhitebu** [vaadin/vaadin-grid#114]
It would be great to be able to set the renderer using a col attribute instead of having to do this in JavaScript.

E.g.

`<col name="balance" header-text="Balance" renderer="_currencyRenderer">`

instead of:

```
ready: function()
{
   this.$.grid.columns[1].renderer = this._currencyRenderer;
}
```

**Comment by jounik** [comment]
Sounds like a great idea, thanks!

We will have to see if this can work in practice, how we can find the correct scope and function to call, because when the `<col>` element is parsed by `<v-grid>` the only scope that we know is for the grid component, and I’m not sure how we can find the function reference.

I think in order for this to work, the renderer will need to be defined using Polymer data binding, e.g.`<col renderer="[[_currencyRenderer]]">`, but I’m not 100% sure if that works.

**Comment by jounik** [comment]
Would #159 be better than this proposal, or would you like both options? I believe the declarative option would be better to have initially, but we could consider adding this later as an alternative method.

**Comment by cbwhitebu** [comment]
I am not sure. Basically, I am hoping that the grid can support doing
everything declaratively (row and cell rendering, event listeners etc).

I know this not a particularly helpful comment

**Comment by jounik** [comment]
We will tackle #159 before considering this. But perhaps a function-based renderer is more versatile in some cases, so I’m still keeping this issue open.

**Comment by elmot** [comment]
Templating in column renderers looks fancy but not enough flexible 
I think the most elegant syntax could look like
```xml
<v-grid>
 <v-col>
   <renderer type="text/html">
       <h1>Some [[template]]</h1>
   </renderer>
   <renderer type="text/javascript">
       cell.innerHTML += "something"
   </renderer>
   <renderer type="text/css">
     h1 {color: red}
   </renderer>

 </v-col>
</v-grid>
```

**Comment by jouni** [comment]
Wontfix. Custom templates in 2.0 cover this need, as you can use `<div inner-H-T-M-L="_rendererFunc"></div>` inside a template.
