### ISSUE TITLE
loading state doesn't get reset in case of network problem with any chunk of data

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1165]
### Description
In case of a network error, vaadin-grid should unset the loading state.

### Expected outcome
Loading state is unset in case of unsuccessful AJAX request.

### Actual outcome
Loading state is set on vaadin-grid.

### Live Demo
https://cdn.vaadin.com/vaadin-grid/5.0.0-alpha3/demo/#grid-data-demos

### Steps to reproduce
1. Go to the 'Assigning Remote/Function Data' demo example
2. Go to the offline mode
3. Scroll down the 'Assigning Remote/Function Data' grid

**Comment by tomivirkki** [comment]
The expected behaviour is a bit unclear. If the grid unsets the "loading" state, it would appear as if the rows are no longer expecting data/the rows have finished loading while in reality they are still lacking data.

Also, grid doesn't know anything about network errors. It's the `dataProvider`'s responsibility to take appropriate action when an XHR errors. In case of the mentioned demo, the `dataProvider` could for example:
1. pass an empty data array back to grid which would make it retry loading the same data when needed
2. keep trying to fetch data from server every 5 seconds or so and invoke the original data request's callback once successful

We could add an `errorCallback` function to the `dataProvider` API, but that would essentially be an alias for invoking the callback function with an empty array.

**Comment by platosha** [comment]
IMO, in case of an error, there should be some way for `dataProvider` to tell the grid to stop waiting for the data. Currently, we don’t have a dedicated API for that. Invoking response callback with empty data, as suggested, works as a workaround, but feels quirky.

I’ve proposed going for Promise-based `dataProvider` API, that should naturally resolve this too.

Because this is a long-existing API issue, and the workaround exists, perhaps it’s too late to fix it for v4 and v5.

**Comment by limonte** [comment]
Resolved by passing the empty items array:

```js
xhr.onerror = () => {
  callback(Array(params.pageSize));
};
```

When network is good, vaadin-grid will try to get the same chunk of data again.
