### ISSUE TITLE
Issue in displaying more than 500 rows

### ISSUE THREAD

**Issue by leelakrish** [vaadin/vaadin-grid#1262]
### Description
Vaadin grid is not displaying more than rows in a page. Those are getting hide.

### Expected outcome
Should show all the rows based in the array of items

### Actual outcome
Displaying only first 500 rows

By checking there is a iron-list-behavior inside vaadin-grid element which has 'maxPhysicalCount' as 500. Unable to pass that value from vaadin grid. Please let me know how this can be done. Thanks

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Starting from the latest beta, you can use attribute `height-by-rows` in order to disable the virtual scrolling inside of the grid. See the "Dynamic Height" [demo](https://cdn.vaadin.com/vaadin-grid/5.0.0-beta7/demo/#grid-data-demos). You can also have a look at "Pagination" [demo](https://cdn.vaadin.com/vaadin-grid/5.0.0-beta7/demo/#grid-pagination-demos) if you want to handle pagination yourself (but that would also make filtering and sorting more complex).

Please pay attention, however, that rendering large set of rows can significantly slow down your performance, especially if you also have a big amount of columns. The grid is designed to use infinite scroll as a feature.

**Comment by jay8t6** [comment]
@web-padawan that is not an option for us, we need to display more than 500 rows on a single page. Is it possible to expose that property on vaadin-grid so we can change that number?

**Comment by tomivirkki** [comment]
If you're using Polymer 1, the latest grid version available is v3.1.0. [Here's](https://cdn.vaadin.com/vaadin-grid/3.1.0/demo/data.html#dynamic-height) how "height-by-rows" is done with v3.1.0 but I strongly encourage against rendering 500 DOM rows in the grid. Virtual scrolling is built in for a good reason (performance with lots of virtual rows).
