### ISSUE TITLE
Can you add vaadin-grid-tree-toggle in vaadin-grid 2.x

### ISSUE THREAD

**Issue by leelakrish** [vaadin/vaadin-grid#1280]
### Description
vaadin-grid-tree-toggle in vaadin-grid 2.x

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by jay8t6** [comment]
+1 this would be a neat feature in 2.x.

**Comment by web-padawan** [comment]
Thanks for the issue. We realise that migration of the whole app to Polymer 2 might be a challenge, and some projects still use Polymer 1.x. But we are currently not inclined to backport feature improvements like this to the 2.x branch, otherwise we would also have to do the same for 3.x which would mean extra effort.

Once we release `vaadin-grid` 5.0.0, which is expected to happen quite soon, we will continue backporting some fixes to the 4.x branch, but all the new features are only expected to be implemented on master branch.

**Comment by web-padawan** [comment]
Closing per above comment. We will only backport bug fixes, not new features to older major releases.
