### ISSUE TITLE
Question: How to test and inspect `<vaadin-grid-cell-content>`?

### ISSUE THREAD

**Issue by tomalec** [vaadin/vaadin-grid#1366]
### Description
 I'm working with custom element that uses `<vaadin-grid>` and have hard time writing tests for it. Are there any materials that helps with writings tests with `vaadin-grid`, or explaining what is the flow of `<vaadin-grid-cell-content>`? I'm trying to check, if cells were rendered in appropriate rows or columns, but there is no clue I can get from investigating the light DOM elements. Those `vaadin-grid-cell-content` seems to appear in random order with strange content (empty ones, ones without stamped `{{values}}`, etc)

There is no `aria-colindex` or `aria-rowindex` set on it.

**Comment by tomivirkki** [comment]
We use the helpers from [this file](https://github.com/vaadin/vaadin-grid/blob/master/test/helpers.html#L24) in grid tests. Especially `flushGrid(grid)` is in constant use as it flushes lots of internal async processes such as the flattened node observer of the light dom.

**Comment by platosha** [comment]
Couple more tips:
- `cellContent.assignedSlot().parentNode` should refer to the actual `<td>` cell from the grid’s shadow DOM. 
- put the relevant information into the cell templates, e. g., row index `[[index]]`, some column name string, and so on. The template content then ends up in the `<vaadin-grid-cell-content>`, from where it is easy to assert.

**Comment by tomivirkki** [comment]
Closing this as it's not an issue/feature request.

**Comment by tomalec** [comment]
Thanks for the hints and support.

> `cellContent.assignedSlot.parentNode` should refer to the actual `<td>` cell from the grid’s shadow DOM.

That's what I end up doing, but it makes my test dependent on very internal, implementation details, also, I need to check things like:

```js
 // is not part of a caption
 !el.assignedSlot.parentElement.matches(`caption>td`) &&
 // is not out of scroller
 !el.assignedSlot.parentElement.matches(`vaadin-grid-outer-scroller td`) &&
 // is part of header, body, footer, or anything
 el.assignedSlot.parentElement.matches(`[part~=${partName}]`)
```

Is there a reason why you are not setting `aria-colindex`, `role="gridcell"`, `role="columnheader"`, etc. on elements exposed to the light DOM? I noticed you are setting roles & co. on `td`. I think it's redundant as `td`s are `gridcell`s by default https://codepen.io/stevef/pen/OmVeJL Shouldn't the ARIA attributes be sen on non-native elements (`<vaadin-grid-cell-content>`)?

**Comment by platosha** [comment]
> Is there a reason why you are not setting `aria-colindex`, `role="gridcell"`, `role="columnheader"`, etc. on elements exposed to the light DOM?

Good question. ARIA is set where the keyboard focus is. Our intention, as far as I recall, was to keep `<vaadin-grid-cell-content>` as lightweight as possible to keep its performance impact small. The only purpose of the `<vaadin-grid-cell-content>` initially was to expose the user’s content in the light DOM while slotting it into the cell. It is not even a registered custom element. So the focusable is the cell, not the cell content element.

If it is important for your use case to know more about where the content belongs, maybe it is fine to look into the grid internals, since this is the `<vaadin-grid>`’s concern to own the rows and cells.

We agreed to keep the `part` attributes in the DOM as stable and documented API for theming purposes, so these should be reliable enough for testing as well. Whereas anything else, such as classes, ids, element names, ARIA attributes are subject to change.
