### ISSUE TITLE
DX tests for detailed events API and cell class generator

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#1477]
Child of #1297

Plan, book, conduct, report findings

**Comment by pekam** [comment]
DX test report: https://docs.google.com/document/d/1dRGpTyQr42YCeoEnOTzq9p94vujk8Q33jv3x8HpDU_A/edit?usp=sharing

Created tickets: #1492 #1493

Also decided that we need architects' opinion on following DX issues:

1. Having to define the `detailedEvents` array before listening to the events can be painful, feels like an extra step
-For some users it took really long to find out why their `detailed-event` listener is not called, after they just copied the listener from the demo without noticing the array definition
-Could this step be removed?
-Eg. with a separate method `addDetailedEventListener(‘click’...`
-Or somehow detect if user adds a listener for an event with `detailed-` prefix?
2. Some people didn’t really like the `detailed` term, but the only suggestion was that the events could be eg. `grid-click` instead of `detailed-click`
-Everyone was able to use the API based on the demo. It’s just that if you only notice the property name, you probably don’t know what it means.
-`cellEvents`? Eg. `cell-click`?
