### ISSUE TITLE
assess vaadin-text dependency 

### ISSUE THREAD

**Issue by christophe-g** [vaadin/vaadin-grid#1511]
`vaadin-grid-filter` imports `vaadin-text-field` (as it is used in the default slot): 
```html
<link rel="import" href="../../vaadin-text-field/src/vaadin-text-field.html">
```

Is is possible to review this and request devs to manually import vaadin-text if they want to use vaadin-grid-filter without providing slotted contend?

For instance, I am happy using `paper-input` as a filtering fields and do not wish to add extras/unused dependencies into my build: 
```html
 <template class="header">
      <vaadin-grid-filter aria-label="code" path="log.code" value="[[_filtercode]]">
           <paper-input no-label-float placeholder="code" value="{{_filtercode::input}}" focus-target></paper-input>
         </vaadin-grid-filter>
   </template>
```

Happy to provide a PR and if that is o.k.

**Comment by christophe-g** [comment]
Thanks a lot for this detailed answer . 

I am not facing any difficulties in using the filter (with or without dataProvider). 

In this post, I am just asking if **importing `vaading-text-field` from within `vaadin-grid-filter` could be avoided** so as to keep number of dependencies lower (e.g. keep application build smaller; avoid importing lumo themes - themselves imported by `vaadin-text-field`)

**Comment by tomivirkki** [comment]
Unfortunately we'll need to import `<vaadin-text-field>` with `<vaadin-grid-filter>` as it's the default UI control for the filter helper component. Requiring users to import `<vaadin-text-field>` separately while they're not directly using it could be confusing. Changing the default control to something else (a native input maybe) could work but that wouldn't look as nice (would require a major bump for the component also).

As mentioned above, if a developer wants to leave out some imports that by default ship with the helper components, the best approach is to use a `dataProvider` and custom UI controls (instead of `items` and the helper components).

**Comment by christophe-g** [comment]
Noted - Thanks !
