### ISSUE TITLE
Crash on chromium v65.0.3325.146

### ISSUE THREAD

**Issue by bisam-rd** [vaadin/vaadin-grid#1530]
Something in vaadin-grid makes chromium v65.0.3325.146 crash.

Repro: navigate to https://vaadin.com/components/vaadin-grid/html-examples/grid-basic-demos

![caption](https://i.imgur.com/SHzjBJ4.png)

Upgrading the chromium version for our client might not be a short term solution for us.
Any suggestions ?

**Comment by web-padawan** [comment]
Hi. This was workarounded in 4f417c0 and 5.0.x version works in Chrome 65, but keep in mind that is bug in Chrome and we recommend updating. Keeping workaround in master is not something we can afford.

**Comment by pleku** [comment]
Hi @bisam-rd if you have major trouble updating to a newer chromium version in the short period, one option might be to try to make a custom version of `vaadin-grid` 5.2 (which I believe you are using?) by cherry-picking that workaround on top of it and using that version instead - but it will be quite a hassle and to cherry-pick it and get that a custom version to be used instead of the webjar that is the dependency for the Java integration `vaadin-grid-flow`.

But you need to consider which option is better for you at the moment. 

Here is the original chromium issue for reference https://bugs.chromium.org/p/chromium/issues/detail?id=817499&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

**Comment by web-padawan** [comment]
Note: the original workaround was to combine small mixins into the bigger one, as Chrome 65 was crashing after some number (like, 25) mixins in prototype chain. It can't be easily cherry-picked, and rather re-applied manually from the latest 5.2 branch, as some code since 5.0.x has changed.
