### ISSUE TITLE
Event "cell-activate"

### ISSUE THREAD

**Issue by Springrbua** [vaadin/vaadin-grid#1536]
### Description
I am using the `vaadin-grid` in Vaadin Flow and I would like to get informations about the active cell.
I have seen, that the `vaadin-grid` supports the `cell-activate` event (See [vaadin-grid-active-item-mixin.html](https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-active-item-mixin.html)). However, this event, in my opinion, is not reliable yet.
It only seems to fires on click, while you can also activate items using the arrow-keys (see [vaadin-grid-keyboard-navigation-mixin.html](https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-keyboard-navigation-mixin.html)).
Also, it does not use the `EventContext`, which gives information about the row and the column (see [vaadin-grid-event-context-mixin.html](https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-event-context-mixin.html)).
Also, it does not seem to be possible to activate a cell programatically, using Vaadin Flow (Java).

### Expected outcome
The `cell-activate`-Event should fire whenever a new cell is activated (focused).
Also, the `event.details` should use the `EventContext`, which includes the `column` and the `item`.

### Actual outcome
The `cell-activate`-Event is only fired when a cell is clicked, the keyboard navigation does not trigger a `cell-activate`-Event.
Also, the `event.detail` does not include the column, but only the row.

### Steps to reproduce
1. Put a `vaadin-grid` element in the page.
2. Add a listener to `cell-activate` of the grid and log the event.
3. Click on a cell to see the output. There is no information about the column.
4. Navigate around using the arrow keys. No event is logged.

**Comment by tomivirkki** [comment]
Hi, `activeItem` is marked as `notify`, meaning that it'll fire an event named `active-item-changed` whenever the property changes https://cdn.vaadin.com/vaadin-grid/5.2.6/#/elements/vaadin-grid#property-activeItem

The property is also not read-only so you can set it programmatically

**Comment by tomivirkki** [comment]
To activate an item with keyboard, you'll need to hit space. Simply moving the focus over a cell doesn't produce any events.

If you're on `<vaadin-grid>` 5.3 then there's a new API for getting contextual information (item, column etc) from any event that occurs in a cell https://cdn.vaadin.com/vaadin-grid/5.3.0-alpha7/demo/#grid-event-context-demos

**Comment by Springrbua** [comment]
Is there any way to get and set the focused cell useing vaadin flow?

**Comment by tomivirkki** [comment]
I don't think there's a Flow api for that, since the web component doesn't have API's for that either

**Comment by Springrbua** [comment]
Thank you for the quick informations.
Is the `getEventContext`-API accessible using Vaadin Flow?

**Comment by Peppe** [comment]
I did an initial PR for having a dedicated event for cell focus: https://github.com/vaadin/vaadin-grid/pull/1564

**Comment by rolfsmeds** [comment]
As a developer
I want to be notified about grid cell focus changes
So that I can do stuff when a grid cell is focused

## Acceptance criteria
- [ ] API for adding a listener for cell focus changes
- [ ] Event that can be used together with Grid.getEventContext to get the event source cell
- [ ] Triggered for mouse, tap and keyboard focus events

## General criteria
- [ ] APIs reviewed [here link to API review documentation, if any]
- [ ] DX tests in Alpha [here link(s) to issue(s) with the description of DX tests, if any]

**Comment by tomivirkki** [comment]
What are the needs for this on the server-side? If we just added all the information obtainable from the event context the server-side API might look something like (perhaps with Optionals):

```java
grid.addCellFocusChangedListener(e -> {
    Person item = e.getItem();
    Column<Person> column =  e.getColumn();
    HeaderRow headerRow = e.getHeaderRow();        
    HeaderCell headerCell = e.getHeaderCell();
    FooterRow footerRow = e.getFooterRow();
    FooterCell footerCell = e.getFooterCell();
    boolean detailsCell = e.isDetailsCell();
});
```

Additional questions
- Since the event name is "cell focus changed", should it also dispatch when a cell loses focus (blur)?
  - Should the event dispatch when you click somewhere outside the grid so it loses the native focus altogether?
  - If it's only about the focus, should it affect the naming ("cell focused")?
- Is this only relevant on "navigation mode" (when navigating the cells with the blue outline active) or also on "interaction mode" where you might have the native focus in an `<input>` inside one cell and then hit tab to focus an `<input>` inside another cell?
  - If it's only about the navigation mode, should it affect the naming ("cell navigation")?

**Comment by rolfsmeds** [comment]
> Since the event name is "cell focus changed", should it also dispatch when a cell loses focus (blur)?

The name would imply that yeah. And thinking of the use case where you want to display something elsewhere in the UI based on the currently focused cell, you probably want to stop displaying that when the cell loses focus (although you'd also have the option to continue display the info for whatever the last focused cell was). So would `getItem()` then return null (or an empty Optional), if the entire Grid loses focus? 

I guess the alternative would be to have a "cell focused" event instead, in which case you'd need to listen for the Grid's blur event if you want to stop showing whatever when that happens?

> Is this only relevant on "navigation mode" (when navigating the cells with the blue outline active) or also on "interaction mode" where you might have the native focus in an <input> inside one cell and then hit tab to focus an <input> inside another cell?

While I'm not necessarily saying it _shoudn't_ work in interaction mode as well, I having trouble coming up with a use case for it.
What would be the behavior if it only worked in navigation mode? When you switch to interaction mode, would there be an event then, and another when you return to navigation mode, but nothing in between?

**Comment by web-padawan** [comment]
Just to clarify the above comment: Flow API for this event was reverted from Vaadin 20 and re-added to Vaadin 21.
