### ISSUE TITLE
ColumnResizeListener

### ISSUE THREAD

**Issue by Springrbua** [vaadin/vaadin-grid#1538]
### Description
It is possible to resize a column, however there does not seem to be an event to get notified about this resize.

### Expected outcome
Resizing a column should fire a `column-resize`-Event, which should contain the new width of the column.

### Actual outcome
The column is resized, but the actual width is not reported back.

### Usecase
I am using the grid in vaadin flow and I would like to be able to get the current column-configuration (column order, column width) on the server.

**Comment by spikeon** [comment]
### Expanded Use Case:
I am using the grid in Vaadin Flow, and I want to persist the user's configuration options across sessions.  I need to be able to store their chosen column widths in my database so that I can make sure that the next time they use that grid, it has the same column widths that they chose.

**Comment by HJK181** [comment]
Same thing here, I also want to store the width's in the browsers localStorage like described here: https://github.com/vaadin/vaadin-grid/issues/497 but the `on-column-resized` event doesn't seam to exists in 5.4.6 anymore.

**Comment by melDavila** [comment]
As "spikeon", I have the same situation:

I am using the grid in Vaadin Flow, and I want to persist the user's configuration options across sessions. I need to be able to store their chosen column widths in my database so that I can make sure that the next time they use that grid, it has the same column widths that they chose.
