### ISSUE TITLE
Theme not applied to Vaadin-button in grid.

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/vaadin-grid#1547]
I have a grid with a Vaadin-button on each row. The Vaadin button is themed (primary) but it is showing as a regular button (grid1).

Oddly enough, if I add another button after the grid, the buttons in the grid are rendered correctly (grid2).

![grid1](https://user-images.githubusercontent.com/6271003/51565681-3b28dd80-1e58-11e9-8c72-a08cc80dcf50.png)
![grid2](https://user-images.githubusercontent.com/6271003/51565682-3b28dd80-1e58-11e9-8447-616630e2f484.png)

Source code attached in zip.

[grid.zip](https://github.com/vaadin/vaadin-grid/files/2784625/grid.zip)

**Comment by web-padawan** [comment]
Thanks for the issue. The `vaadin-grid` is not magically importing `vaadin-button` for you, as it is not using it internally (unlike the checkbox, which you can see as themed). 

I will move this to Flow counterpart, however not sure if that is actually an issue, or the expected result caused by the way how unstyled components and themes are being imported in Flow.

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-grid-flow#489
