### ISSUE TITLE
How can I use variables inside a template?

### ISSUE THREAD

**Issue by npsedhain** [vaadin/vaadin-grid#1643]
```js
<vaadin-grid-column width="500px">
            <template class="header">
                <span>Progress</span> 
            </template>
            <template>
              {{item.progress}}      // this works
              <span class=${getColor(item.progress)}></span>   // this doesn't work
            </template>
</vaadin-grid-column>
```

How can I access the variable `item.progress` inside the template?

**Comment by Haprog** [comment]
See the Polymer documentation for the proper syntax for data binding attributes and properties:
- https://polymer-library.polymer-project.org/2.0/docs/devguide/data-binding (if using Polymer 2, e.g. Vaadin 10-13 or Vaadin 14 with compatibility mode enabled)
- https://polymer-library.polymer-project.org/3.0/docs/devguide/data-binding (if using Polymer 3, e.g. Vaadin 14 without compatibility mode)

You're probably looking for:
```html
<span class$="[[getColor(item.progress)]]"></span>
```

If you need more help with our components, instead of reporting an issue, please ask e.g. in [vaadin/web-components Gitter](https://gitter.im/vaadin/web-components) or [Vaadin Forum](https://vaadin.com/forum/category/9848927/05-components)
