### ISSUE TITLE
Grid scrolling within Firefox

### ISSUE THREAD

**Issue by StefanCov** [vaadin/vaadin-grid#1645]
### Description

I have created a tile view which works perfectly within Chrome but not when using Firefox. The scrolling within Firefox seems to scroll 3 rows for each scroll event. This is an issue as the rows for the tile are responsive and have large heights set to them. This means it will skip row 2 and 3 even if it is not visible to the user. Chrome somehow scrolls by pixels and makes the experience much smoother even for a normal grid. 

Is this a bug or intended for the grid? If it is intended, how would I get Firefox to scroll more like Chrome within my project?

**Comment by Haprog** [comment]
What OS are you on?  
Which version of Firefox and Chrome you tested?  
Are you talking about scrolling with a mouse wheel or something else?

Can you share a code example which reproduces the issue you have? Or maybe a short screen recording of how it looks on Firefox and Chrome for you?

Do you get the same issue (scrolling behaviour difference in Chrome and Firefox) in the grid demos here https://cdn.vaadin.com/vaadin-grid/5.4.8/demo/#grid-basic-demos ?

Scrolling behaviour might depend on which kind of device you use for scrolling (mouse wheel, keyboard, touchpad), what operating system you are on, and there may be scroll related configuration options in either you OS or browser which affects the outcome.

I just tested scrolling on the above demos on latest Chrome and Firefox on macOS. If I scroll with touchpad, the scrolling is smooth on both. If I use a regular mouse wheel to scroll then Firefox seems to scroll 1 grid row at a time, but Chrome scrolls some smaller steps (smaller than a grid row).

I can see this may be a problem if it scrolls more than 1 row at a time for you or if the rows are tall. Not sure if we can easily affect this somehow, needs a bit more investigation.

**Comment by StefanCov** [comment]
- Windows 10 Pro
- Latest Versions of Firefox (68.0.2), Latest version of Chrome (76.0)
- Yes, scrolling with a mouse

- On the example link you provided 1 scroll event will produce this:

![image](https://user-images.githubusercontent.com/54804121/64118494-b1e36d00-cd8f-11e9-9129-55e59c8cc7d7.png)
To this:
![image](https://user-images.githubusercontent.com/54804121/64118549-c6c00080-cd8f-11e9-9a09-ab30eaf23012.png)

I hope it doesn't come down to the mouse as this is very hard to predict hardware devices for a user. It would be good if it scrolled per pixel like Chrome but it doesn't seem to do that. It also makes the scrolling experience smoother if not using the default grid height.

**Comment by Haprog** [comment]
This seems to be related to old fix https://github.com/vaadin/vaadin-grid/issues/883

Firefox by default follows the mouse scrolling settings that are set in Windows (which is probably defaulting to "scroll 3 lines at a time"). This is the `deltaMode` of `DOM_DELTA_LINE` in `wheel` event (https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaMode).

According to [spec for `DOM_DELTA_LINE`](https://www.w3.org/TR/DOM-Level-3-Events/#dom-wheelevent-deltamode):
> The units of measurement for the delta MUST be individual lines of text.

At least in Firefox (when scrolling a page) this seems to be interpreted so that one unit (in `DOM_DELTA_LINE` mode) is equivalent to the default font-size set in browser settings (`16px` if not modified by the user). It does not seem to matter what is set as the font-size for `html` or `body` elements on the page, it always uses the default font-size set in browser settings so scrolling speed is consistent on all sites. So if the font-size in browser setting is set to 16px the smallest amount you can scroll with mouse wheel is 16px (if OS mouse settings is set to scroll 1 line at a time). In your case if your mouse is set to scroll 3 lines at a time, then it should scroll 48px at minimum (assuming you haven't changed the font-size in Firefox preferences).

I think we can consider this behaviour in `vaadin-grid` as a bug since now it interprets the height of a unit in `DOM_DELTA_LINE` mode as one grid row, but it should use the browser font-size instead (usually 16px) so that it's not dependent on grid row height.

It also seems that there's no nice way to detect what is the browser's default font size when we don't know if font-size has been overridden for `html` or `body` in some stylesheet. Though apparently it can be done in a slightly hacky way by creating an `iframe` https://stackoverflow.com/a/37474225/1362634

If we can't find a better way to check the default `font-size` I think we should use the `iframe` approach to read it and then use that as the base unit for when the browser requests `DOM_DELTA_LINE` scrolling mode. Needs to be also tested on different browsers in Windows an macOS at least (with a mouse).

**Comment by StefanCov** [comment]
I see, font size would make sense and would allow for my grid to scroll without skipping rows. 

I'm guessing having this labelled as a bug means that you will be looking to fix this in the future? I could hold off on the tile view for now until the font-size scrolling on a grid within Firefox is fixed.

**Comment by Haprog** [comment]
I'm working on fixing this now. It should get fixed first for vaadin-grid v5.5 (which is now in alpha) and backported to v5.4 and v5.0. I would expect this fix to be released either later this week or next week.
