### ISSUE TITLE
Multiselect grid with callback data provider does not have a select all checkbox

### ISSUE THREAD

**Issue by mihaisavezi** [vaadin/vaadin-grid#1678]
### Description

Multiselect grid with callback data provider does not have a select all checkbox.
Same issue as here in the [#java  version](https://github.com/vaadin/vaadin-grid-flow/issues/549)

I understand the difficulties of selectAll when handling data with dataProvider. Still some documentation around this should be made available.

We use this in our own paginated web component built on vaadin-grid.

```javascript

class WebComponent {

...

render() {
    return html`
      <div class="grid-container">
        <vaadin-grid
          @click=${this.onRowClicked}
          .size=${this.config.totalSize}
          .items=${this.items} // this is the key
          .pageSize="${this.config.pageSize}"
          .dataProvider=${(data, callback) => {
            this.items && callback(this.items, this.items.length);
          }}
        >
          ${this.config.enableSelection
            ? html`
                <vaadin-grid-selection-column></vaadin-grid-selection-column>
              `
            : html``}
          ${this.renderColumns(this.config.columns)}
        </vaadin-grid>
      </div>
      <div class="pagination-wrapper">
        ...
      </div>
    `;
  }

```
### Workaround
The fix for us was to define the items array as well, so it passes the verification in
vaadin-grid-selection-column/onDataProviderChanged
```
...
_onDataProviderChanged(e) {
        this._selectAllHidden = !Array.isArray(this._grid.items);
      }
```

**Comment by tomivirkki** [comment]
Hi, the `<vaadin-grid-selection-column>`'s "select all" checkbox is intentionally hidden when `dataProvider` is used. But you can implement the selection column with `dataProvider` as described in the "Custom Selection with Data Provider" example at https://cdn.vaadin.com/vaadin-grid/5.5.0/demo/#grid-selection-demos (Note that the verbosity is due to using vanilla JS. Appears you're using Lit so the implementation should be cleaner.)

Setting both `dataProvider` and `items` sounds dangerous and might even result in unexpected bugs occurring.
