### ISSUE TITLE
Details row is not visible when using Shadow DOM

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-grid#194]
Copied the full source of the [Row Details](https://cdn.vaadin.com/vaadin-components/latest/vaadin-grid/demo/details.html) example and tried running it with ```?dom=shadow``` enabled. The result is that Grid reserves correct height of free space for the details, but nothing is visible on screen. See the attached screenshot.

![screen shot 2015-10-05 at 11 46 02](https://cloud.githubusercontent.com/assets/368220/10276226/d2adffd6-6b56-11e5-9f9c-58a1ede587cc.png)

**Comment by jounik** [comment]
1d research for one person should be enough to figure out how to proceed.

**Comment by tomivirkki** [comment]
Here's the problematic line, a CSS selector that hides details row cells (with native shadow DOM enabled):
https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid.html#L233

With _shady DOM_ the selector gets enforced with .style-scope and .vaadin-grid but because Grid only adds the styles to data row cells (erroneously excluding details rows), details row cells aren't matched and thus stay visible.

However, with native shadow DOM enabled the selector isn't enforced and it by default hides all the table cells. Only the data row cells match the following selector that unhides hidden cells so they work fine.
https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid.html#L237

Solution: Enforce the mentioned selectors to only match data row cells (... td.vaadin-grid-cell {...} )

Better solution: Investigate why we even have such CSS rules that hide+unhide the data rows. If they're no longer needed, remove them instead.

**Comment by jounik** [comment]
Phew, glad it’s just a simple CSS issue.

The original reason for hiding them is to show the underlying loading spinner, and fade them in when data is actually available for those rows. The transition was probably removed at some point. So perhaps a row is selected even though it doesn’t have data yet, and that would visibly overlap the loading spinner.

**Comment by jounik** [comment]
So I would lean on the side of fixing the selector instead of removing the styles.

**Comment by jounik** [comment]
And actually, the transition is there still, also: https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid.html#L308

**Comment by tomivirkki** [comment]
Ah, so it seems
