### ISSUE TITLE
JS error occurs when grid columns are re-created

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/vaadin-grid#1981]
I have a use case, where grid columns are dynamically created each time user makes some selection in the view.
Normally it works fine, but when the columns are re-created, if also a new row should be added, then the following error appears: **`Cannot read property '__getRowModel' of undefined`**

It seems to be because of `vaadin-grid-column`'s `grid` property is not set.

Here is a sample code to reproduce the issue:

	private Grid<Bean> grid;
	private List<Bean> beans;

	public SampleGridTest() {
		grid = new Grid<>();
		beans = new ArrayList<>();
		beans.add(new Bean("Hello"));
		Button addButton = new Button("add");
		addButton.addClickListener(evt -> {
			beans.add(new Bean("Hello"));
			grid.removeAllColumns();
			grid.addColumn(Bean::getValue).setHeader("Bean");
			grid.setDataProvider(DataProvider.ofCollection(beans));
		});
		grid.addColumn(Bean::getValue).setHeader("Bean");
		grid.setDataProvider(DataProvider.ofCollection(beans));
		add(grid, addButton);
	}

Vaadin version : 13.0.1
Browser : Chrome Version 72

**Comment by martinisraelsen** [comment]
I'm experiencing this issue as well.

**Comment by tomivirkki** [comment]
The error is caused by the grid [manually invoking](https://github.com/vaadin/web-components/blob/7561568d425f2bd304b6f1223baa176a011c7b9a/packages/vaadin-grid/src/vaadin-grid.js#L511) `notifyPath` for all columns regardless if they're detached or not. This can be fixed by also checking that the column element is connected for example with `c => c.parentElement && c.notifyPath && ...`
