### ISSUE TITLE
Add support for fixed page length queries

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#199]
Currently, vaadin-grid sets index and count based on its needs. This makes it very difficult/awkward to integrate with APIs that are designed to work with a fixed page length. Many server side frameworks like Spring Data also offer built in pagination support that assumes fixed page length.

**Comment by vaadin-marcus** [comment]
One option would be to allow user to specify a page length for the datasource:
`grid.data.pagelength = 15`

After this, the data source function would get as parameters `page` and `size` instead of `index` and `count`. This should make it very simple to integrate to a paged data source.

**Comment by jounik** [comment]
Proposal:
```
grid.pageLength = 50;

grid.items = function(params, callback) {
  fetch("data/from/url?page=" + params.page)
    .then(function(response) {
      callback(response.json());
    });
}

```

**Comment by Saulis** [comment]
@jounik would need prototyping, but after a quick glance this should be a fairly simple task just by implementing a [CacheStrategy](https://github.com/vaadin/vaadin/blob/master/client/src/com/vaadin/client/data/CacheStrategy.java) that supports paging.

**Comment by jounik** [comment]
2 person days research.

**Comment by tomivirkki** [comment]
Current prototyping progress at feature/pagesize branch.
https://github.com/vaadin/vaadin-grid/tree/feature/pagesize

CacheStrategy is needed to increase the amount of items the grid keeps in memory before/after the visible viewport, but that's about all it does.
https://github.com/vaadin/vaadin-grid/blob/feature/pagesize/java/src/main/java/com/vaadin/elements/grid/data/GridJsFuncDataSource.java#L37

Grid isn't originally designed for paged data but it can request any number of rows starting from any index at any time so some hackery is required.

The prototype's approach is to intercept/cancel requests made by Grid and analyse the requested range for required pages for covering the range...
https://github.com/vaadin/vaadin-grid/blob/feature/pagesize/java/src/main/java/com/vaadin/elements/grid/data/GridJsFuncDataSource.java#L77

...and invoking a new request who's firstRowIndex is the start index for a page and numberOfRows is the page size
https://github.com/vaadin/vaadin-grid/blob/feature/pagesize/java/src/main/java/com/vaadin/elements/grid/data/GridJsFuncDataSource.java#L92

...once the new request is intercepted by the same logic, it doesn't get canceled because it's a valid one-page request and process continues normally
https://github.com/vaadin/vaadin-grid/blob/feature/pagesize/java/src/main/java/com/vaadin/elements/grid/data/GridJsFuncDataSource.java#L83

...newly requested data mustn't create a gap between the existing cached range so the requested page is selected either from the beginning or the end of the range
https://github.com/vaadin/vaadin-grid/blob/feature/pagesize/java/src/main/java/com/vaadin/elements/grid/data/GridJsFuncDataSource.java#L90

Things work fine most of the time but there's one problem remaining: if the user scrolls the viewport fast upwards (by dragging the scroller), grid gets caught in an eternal request loop so some debugging is still needed.

**Comment by tomivirkki** [comment]
Debugged this with @saulis
Working prototype at https://github.com/vaadin/vaadin-grid/tree/feature/pagesize

Missing:
- Tests
- Api documentation
- Demo

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 uses fixed page lengths for the dataProvider requests.
