### ISSUE TITLE
Simplify selection listener 

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#201]
One of the most common uses for a selection event is getting the selected item. Right now this requires too much work. 

```
if(grid.selection.selected().length === 1){
grid.data.getItem(grid.selection.selected()[0], function(err,item){return item;}}
```

Please include a way of getting the item from the event. Maybe the event could include a selectedItems array: 
`[{id: 0, getItem: function(){..}}]` 

This way, we could have a convenience function for getting the item without having to incur the overhead of resolving the items during the even.

**Comment by vaadin-miki** [comment]
Please add `value-changed` and `itemValuePath` attributes (naming consistent with `combo-box`). The way I would like to see it work is the following:

`itemValuePath` specifies the column name to be returned in `value-changed` events. It would work exactly the same way as it does in `combo-box`. If that attribute is not present or not specified, by default the event can contain row index, for example.

`value-changed` would be called every time selection changes (instead of or in addition to current `selected-items-changed`), and would include whatever is the current selection in the event itself (available through `event.detail.value`). Extra awesomeness points if this is aware of the selection mode - so it contains an array in multi selection mode and a single value in single selection mode - but I would be fine with it always having an array.

The typical use case would be to populate the table with data from a database table. Each row has a unique id, which I currently can pass to `combo-box`, but cannot to the grid.

I guess that another common use case would be to substitute selection component from `combo-box` to `grid` - and I would expect that it does not force rewriting events related to value changes.

Final word, the support for [Vaadin Elements in Ruby](https://github.com/vaadin-miki/vaadin-elements) would greatly benefit from this feature.

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 has a much improved selection API.
