### ISSUE TITLE
Grid not scrolling to the top when calling setItems

### ISSUE THREAD

**Issue by Ramonrune** [vaadin/vaadin-grid#2035]
When i'm calling grid.setItems(list), grid does not scroll at top when a new list of items is setted. Basically, i have a grid and two buttons, when i click in each button, a new list of items must be updated.
Example:

**Grid code**
```
grid.addColumn(new ComponentRenderer<>(documentModel -> {

	TextField textField = new TextField();
	textField.addClassName("font-style");
	textField.setWidth("100%");
	textField.setValue(String.valueOf(documentModel.getDocId()));
	return textField;
	
})).setHeader("Access key").setFlexGrow(0).setWidth("400px").setKey("doc_id").setSortable(true)
				.setResizable(true);

grid.addColumn(new ComponentRenderer<>(documentModel -> {

	Div div = new Div();
	div.setWidth("100%");
	if (String.valueOf(documentModel.getDocNumber()).isEmpty()) {
		div.setText("Não disponível");
	} else {
		div.addClassName("font-style");
		div.addClassName("n-doc");
		div.setText(String.valueOf(documentModel.getDocNumber()));
	}
	return div;

})).setHeader("Document number").setFlexGrow(0).setWidth("150px").setKey("doc_number").setSortable(true)
				.setResizable(true);
```

**Update items code (when clicking on button):**

```
grid.setPageSize(1000);

List<DocumentModel> documentList = //code to load data

grid.setItems(documentList);
```

**Expected:**
Grid scrolling at first index when button is clicked.

**What is happening:**
Grid is scrolling to index 4 of grid, hiding the first elements.

I'm using Vaadin 10.0.2 and Google chrome v67.0.3396.99 (Oficial release) 64 bits.

**Comment by tomivirkki** [comment]
There's an explicit API `scrollToStart()` (since https://github.com/vaadin/vaadin-grid-flow/pull/778) that can be used to reset the grid's scroll position to 0.

Normally, the grid's scroll position would remain unchanged whenever new items are set. Updating the pageSize every time new items are set (`grid.setPageSize(1000);`) might have caused some shifting in the scroll position in the case of the example. If, for some reason you need to change the Grid's pageSize, it should ideally be done once, and before user interaction.
