### ISSUE TITLE
TreeGrid selection support for all nodes, not just leaves

### ISSUE THREAD

**Issue by TLN2** [vaadin/vaadin-grid#2070]
## Description
Vaadin TreeGrid (https://vaadin.com/components/vaadin-tree-grid) has a way of behaving that is confusing in general and making it completely unusable in what I thought is a very typical, everyday scenario: A windows-explorer-like directory tree.
We're not trying to use it as such, but it's a good example to explain, i.e. one that is easy to understand and which behavior we're trying to get.

Shortcomings of current version:
- In hierarchy column there is no separation between icon click and label click.
- Click expands and collapses but does not select.
- With the workaround suggested in https://vaadin.com/forum/thread/17580341/treegrid-enable-to-select-parent-item-by-clicking-on-it you can get it to select on click, but it's confusing because if you only want to collapse the selected item, it also gets unselected. (Even with the workaround TreeGrid behaves in an irritating way, even though with patience you can get done what you want to do.)
- Confusing event types for selection handling: addItemClickListener() / addSelectionListener() / asSingleSelect().addValueChangeListener()
- As it seems there is no way to suppress the default expand/collapse behavior or the default select/unselect behavior to replace it with your own one.

### For inner nodes (=have children)
Click on icon:
- Toggle expansion status
- Don't change current selection

Click on label if currently not selected:
- Select.
- Expand if collapsed.
- Keep expanded if expanded.

Click on label if currently selected:
- Expand if collapsed

### For leaves (=have no children)
Click on label:
- Make selected if not selected.
- Keep selected if already selected.

### For inner nodes (=have children)
Click on icon:
- Toggles expansion status
- With workaround: Toggles selection.
- Without workaround: Doesn't change current selection.

Click on label if currently not selected:
- Exactly like click on icon

Click on label if currently selected:
- Exactly like click on icon

### For leaves (=have no children)
Click on label:
- Toggles selection status

I'm not suggesting that the above should be the *default* behavior of TreeGrid, but given how intuitively above behavior can be used because we're doing it every day in Windows Explorer and how well proven it is, it should be possible to get this behavior somehow by using custom listeners in a clever way or the like. Currently I'm very sure it's impossible to do that, at least if you don't want to use dirty hacks.

**Comment by jcgueriaud1** [comment]
If you want to expand/collapse only on the icon, there are a couple of workarounds here:
https://github.com/vaadin/vaadin-grid/issues/1806

I think the workaround in Java and the grid as single select you have this behavior:

For inner nodes (=have children)
Click on icon:
- Toggle expansion status
- Don't change current selection

Click on label:
- Toggle selection

But it does not expand + select, if collapse on label click.

Do you have an online demo of a tree component of your expected behavior?

**Comment by TLN2** [comment]
Thanks. The first workaround might be a start, but it looks complicated, and of course it's what you don't want to do when trying to code a robust application that doesn't break easily with future Vaadin updates or the like. But I'll try it, it's better than nothing.
The second workaround will not work for us because it will block mouse selection as well.

Regarding your question "Do you have an online demo of a tree component of your expected behavior?":
Directory tree in a Windows Explorer (left-hand pane).

Windows is so omnipresent that I think this example is excellent in all of the following respects:
- Accessibility for trying it out somewhere.
- Credibility that many users are intuitively used to exactly this style of handling tree data.
- Credibility that it's a GUI where a lot of great UI designers have put a lot of thought into.

Actually it can be summarized with three basic mouse rules:
- After a click on the label of an item it's always expanded and selected.
- In particular: No click on the label of an item ever collapses or unselects it.
- Click on the front icon toggles expansion status and leaves selection untouched (even if this selection is somewhere completely different).

Keyboard handling would be like this:
- Up and down arrows do what you'd expect.
- Right arrow expands the current item if it's collapsed. If it's expanded, right arrow descends into it (selects first child item).
- Left arrow collapses the current item if it's expanded. If it's not expanded, left arrow jumps to the parent item.

**Comment by jcgueriaud1** [comment]
I'm on Mac 😄  I will check on a Virtual Machine.

The first workaround is not that complicated for a text node `addNoClickHierarchyColumn`, it's only one Java function overridden and the risk of changes is, in my opinion, manageable.
It's ugly for a renderer `addNoClickComponentHierarchyColumn`, (if you need an icon or component ...).

Basically the TreeGrid expands/collapses when the user clicks on a component `vaadin-grid-tree-toggle` which contains by default the entire column. And you want to change the behavior of the expand/collapse, so this is the component to change.

It's hard to choose what is the "correct" behavior because you can use the TreeGrid as a Tree (one column like the explorer) or like a data grid.
For example, I can expect to select the text on double click in a data grid or enter in a editor mode, or expand the node ... 
It's quite the same for the left and right arrow. Currently it navigates to the previous/next column.

I think most of your need can be done. The left arrow is probably the hardest (_jumps to the parent item_ )and I'm not sure if it's doable. Right arrow won't be pretty also, but it's doable.

**Comment by TLN2** [comment]
Your first workaround is doing the trick for us. Thanks a lot. Keyboard handling isn't absolutely necessary. And also, since we can get a long with text-only labels, GridHelpers is not too complex. I just removed the component-related methods.
I combined the approach with an event handler that expands an item when it's selected, and it feels really smooth now.

Your remark regarding "correct" behavior is definitely true: Change the behavior, and you'll make people unhappy that are completely happy with the current TreeGrid. There's no one-fits-all solution but there are several valid approaches.

What I can suggest at this point: Extract Expand/Collapse and Select/Unselect behavior into an interface that can be plugged into any TreeGrid. It should have clever methods that inform about clicks and key presses and tree items involved, so that the implementation can decide how to change the tree state based on that. TreeGrid shouldn't do anything on its own in that regard but delegate everything to the interface implementation plugged into it.
You could provide a default implementations for current behavior. Then there could be one mimicking Windows as described above. Also, I would guess there are operating system tree components on Mac that most Mac users are used to, so there could be an implementation mimicking them as well. And ideally users can easily write their own ones or extend one of the provided ones.

Taking everything together I don't see a better alternative. Trees are too complex to say you cover only a small fraction of cases and users should write their own if they're not happy. Hacky workarounds are not sustainable as a standard approach either, even if they're proven to work for the time being. And the interface idea doesn't seem too complex to implement to me, given the huge improvement it would mean for TreeGrid users. Last not least it could be done in a way that doesn't change anything for existing applications, so it could be perfectly backwards compatible.
Thanks.

**Comment by jcgueriaud1** [comment]
Good :).

I also think the TreeGrid is more a Grid with some hierarchical features and it's hard to use it as a Tree (like an explorer Tree).
Putting these 2 components (a Grid and a Tree) in one makes things really hard.

**Comment by rolfsmeds** [comment]
Thanks for the ticket @TLN2, there's a lot to unpack here, but, without going into too much detail, I'd like to close this issue in favor of more tightly scoped ones:

1. There's already a ticket for separating expansion toggle click and 1st column content click: https://github.com/vaadin/vaadin-grid/issues/1806. Selection isn't covered there, but if that separation is made, I think it would make sense for content click to toggle selection while the expansion toggle only toggles expansion. If you want to expand a collapsed parent node on selection, that should be easy enough to do in an eventlistener.

2. Would you mind creating a separate ticket about extracting the selection and expansion behavior into an interface? While I get that it would be ideal by giving developers maximum configurability, it's also a much bigger change so I wouldn't want it to block fixing the simpler expansion/selection fix.

This issue is also related btw: https://github.com/vaadin/vaadin-grid/issues/1934.

**Comment by TLN2** [comment]
Okay, thanks for being open to my suggestion. I created #2073. Closing this one. Thanks again.
