### ISSUE TITLE
Grid should offer default sorting if using array data source

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#212]
It would be very convenient if the Grid supplied a default comparator for sorting Strings/Numbers/Dates in natural order. The user could always supply their own version if they wanted, but it would make the 90%+ use case much easier.

**Comment by Saulis** [comment]
As discussed with @platosha and @jounik , here's a proposal to start working with:

Similar to the filtering proposal #255 we could have a public function which defines the sorting method. This function could be internally used when using items arrays and it by default compare the columns based on their string representation. Sorting method could be overridden by the user.

Also discussed changing the current `sortOrder` structure from `[{ column: 0, direction: 'asc' }]` to contain the `name` of the column rather than the index.

Changing the sort order will fire `sort-order-changed` event and with array data sources it would also trigger sorting implicitly.
