### ISSUE TITLE
Migrate from deprecated jsInterop to the JS_RC version

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#230]

**Comment by manolo** [comment]
We should migrate from jsInteropMode=JS to jsInteropMode=JS_RC

**Comment by manolo** [comment]
At the same point we should take advantage of :
 - @JsFunction and remove all the stuff related with wrapping/unwrapping functions
 - New JsInterop native type syntax for avoiding JSNI at all

**Comment by manolo** [comment]
- First step: change annotations from jsinteropMode=JS to JS_RC
  - That is a almost trivial step since there is a equivalence and we already some experience when porting gwt-api-generator.
  - But unlike the generator we are exporting instead of using external JS which implies an extra issue: 
    In new jsInterop exporting is disabled by default in order to protect gwt projects of excessive js size, so in order to enable export you have to add the -generateJsInterop flag.
    Unfortunatelly it's not available in gwt-maven, so we NEED to patch it before going ahead
    https://docs.google.com/document/d/10fmlEYIHcyead_4R1S5wKGs1t2I7Fnp_PaNaa7XTEk0/edit#heading=h.o7amqk9edhb9
    https://github.com/gwt-maven-plugin/gwt-maven-plugin/issues/123
  - We can leave both annotations in sources and compile with JS until gwt-maven is ready. We already have the double annotation solution in gwt-api-exporter

- Second step: use JsFunctions instead of JsWrappers
  - When passing functions from JS we are wrapping then with customised objects like `GridJsFuncDataSource`, with JsFunction we could remove all JsUtils.jsni calls among as probably the wrapCallback and use interfaces instead.
  - Problems: Grid does not have callback interfaces but abstract classes, which cannot be used in JsInterop, so we would need to continue wrapping it.
  - We can use JsFuntions with the former JS mode. So step#2 can be accomplished before step#1

- Third step: remove JSNI
  - In new jsInterop it's possible to directly map js methods to native java definitions. We have a couple of methods in JS.java and JSArray.
  - We are using some utilities from gwt-query which probably we could replace with native implementations, but I don't see the need.
  - We could skip this step.

### Conclusions

1. We definitively should accomplish  step#1 because support for old jsinterop is being unstable in each snapshot build and will be removed before 2.8.
2. It's very convenient to start working with JsFunctions which simplifies the code
3. JSNI would not be worth until GWT releases Elemental2.0 which wont be released in 2.8.0 but 2.8.1
