### ISSUE TITLE
Run unit tests nightly

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#289]
Currently we run the test for every patch/PR. We should run the tests each night as well to catch any breaking changes Polymer makes that affect the grid.

**Comment by Saulis** [comment]
We should add a scheduled build to TeamCity which triggers builds through Travis API

**Comment by manolo** [comment]
I already added a task at https://nightli.es/ let see if it runs the task nightly

**Comment by Saulis** [comment]
Nice!

**Comment by jouni** [comment]
I think we are deploying vaadin-core-elements#master to CDN every day, right? But are we running the tests for those builds, and do we get the reports from those builds anywhere?

If yes, please close this issue. If not, I think we should move this issue to the vaadin-core-elements repo, as it relates to all elements, not just to vaadin-grid.

**Comment by platosha** [comment]
Travis runs the tests nightly and reports failures when they happen, see: https://travis-ci.org/vaadin/vaadin-grid/builds. I’ve just enabled them for the split-layout and the context-menu, now all the elements have these nightlies.

Although this is not related with the CDN deployment, the matter of this issue was solved.
