### ISSUE TITLE
Editor feature visual design

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#293]
We need visual designs for the row editor feature.

Demo of the buffered editor: http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/item-editor
Demo of the unbuffered editor: http://vasa.demo.vaadin.com/grid-unbuffered/

We need to design a Material Design inspired versions of those.

**Comment by tuomasnironen** [comment]
https://www.google.com/design/spec/components/data-tables.html#data-tables-interaction

**Comment by tuomasnironen** [comment]
[Visual designs for the grid row (and cell) editor](https://drive.google.com/drive/u/0/folders/0BzkWbWvgmkIxdUY3YU40YUJoN1k)

**Comment by tomivirkki** [comment]
Did some technical prototyping on cell editor right here https://github.com/vaadin/vaadin-grid/tree/cell-editor-proto. The easiest solution seems to be using the built-in row editor and placing a custom cell-editor as the widget to a single cell at a time.

The trickiest part is taking care of the placing of the custom editor when it's wider than the actual edited cell (so that it doesn't get clipped for example). The proto handles this ok but the calculation should be improved/polished.
