### ISSUE TITLE
Elements with nested content don't work with the Light DOM configuration table on Shady DOM

### ISSUE THREAD

**Issue by Paranaix** [vaadin/vaadin-grid#329]
Using a `<paper-menu-button>` inside a `<thead>` or `<tfoot>` will cause that no renderer is called and the trigger element of the menu-button to be empty (making the menu button invisible as well).

**Comment by Saulis** [comment]
Looks like custom elements which use `<content>` injection don't work in Shady DOM because `Polymer.dom` API isn't being used when header cell contents set.

As a workaround, you can either wrap the `<paper-menu-button>` in a custom element or you can manually set the header cell contents with `grid.header.getCell(0,0).content = ...` API.

Here's an example how the latter can be done: http://plnkr.co/edit/m9Uceid39Sswwueny0VO

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version does not have this issue.
