### ISSUE TITLE
grid consumes events

### ISSUE THREAD

**Issue by Paranaix** [vaadin/vaadin-grid#330]
It's currently impossible to have some buttons in the footer/header like this and registering event handlers the usual way with Polymer:

```
<tfoot>
  <tr>
    <th>
      <paper-button id="test">Foo</paper-button>
    </th>
   </tr>
</tfoot>
```

Neither does setting `listeners` works, nor does directly setting `on-tap`/ `on-click` on the attribute works. Registering them using `listen` / `unlisten` doesn't work as well:

```
attached: function() {
    this.listen(this.$.test, "tap", "_onEvent");
 },

detached: function() {
    this.unlisten(this.$.test, "tap", "_onEvent");
},
```

The only way I how i could got this to work was:

```
attached: function() {
    this.listen(this.$.grid.$$("#test"), "tap", "_onEvent");
 },

detached: function() {
    this.unlisten(this.$.grid.$$("#test"), "tap", "_onEvent");
},
```

However, while this works initially, **clicking anywhere** inside the grid except on the button will stop the event handler from being called any further.

**Comment by tomivirkki** [comment]
The problem in this case is that &lt;vaadin-grid&gt; currently only copies the inner HTML from inside the &lt;table&gt; configurator element to the grid header instead of using the actual elements. So data binding will not work as it is now.

There's actually an [experimental branch](https://github.com/vaadin/vaadin-grid/tree/fix/data-binding) where this is already resolved.
(can be installed with 'bower install vaadin-grid#fix/data-binding" for example)
Notice that the branch is still unfinished and might bring in some other issues.

If you want to work with the current 1.0 and still utilize data-binding, you can define the button outside the <vaadin-grid> element and manually place it in the header with grid.header.getCell(...).content

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version does not have this issue.
