### ISSUE TITLE
Styling when using Shadow DOM

### ISSUE THREAD

**Issue by Juravenator** [vaadin/vaadin-grid#337]
vaadin-grid allows us to set row and cell classes in function of their content so we can style them (as described in https://vaadin.com/docs/-/part/elements/vaadin-grid/sizing.html).

However when Shadow DOM is enabled these classes are in the local DOM and inaccessible for us to write CSS code against.

Is there any way to get around this or solve this issue?

**Comment by jounik** [comment]
That’s unfortunately true. The internal implementation was done before there was a need for us to consider shadow DOM (as a part of the Vaadin Framework, a couple of years ago), and we haven’t gotten around to refactoring the DOM handling to take support this.

As the `/deep/` combinator is also being deprecated, I’m not aware of any workarounds for this limitation. The only option is to refactor the DOM element rendering quite heavily in the Grid.java and [Escalator.java](https://github.com/vaadin/vaadin-grid/blob/master/java/src/main/java/com/vaadin/client/widgets/Escalator.java) classes.

**Comment by jouni** [comment]
Hi @mbana 

This is an unfortunate limitation for grid 1.x. But I’m happy to report that this will be completely fixed in grid 2.0, which you can try out already: https://github.com/vaadin/vaadin-grid/releases/tag/v2.0.0-pre.1

You can follow the progress from the "2.0-dev" branch, as well as from issues tagged with the "2.0" label.

**Comment by jouni** [comment]
I don’t think we will add the support for the 1.x branch, so I’m closing this issue. Please try grid 2.0 and provide us feedback about it, so we can get that out sooner and with better quality than the current 1.x version.

**Comment by mbana** [comment]
ok, i've tried it out. a few questions:

- if i bind to size, e.g., `size="{{collection.length}}"` and i then clear `collection` it seems like the list `<td>` still remain in the dom.

- i don't find the examples to be simple enough. i am looking at, https://github.com/vaadin/vaadin-grid/blob/v2.0.0-pre.1/demo/index.html. let's say i wanted to do the following: just keep pushing items onto `collection` and have the grid update. it seems like, i could be wrong here, i will need to capture the `callback` argument so that i can use it later, like so:

```js
let callbackDeferred;
grid.dataSource = function(opts, callback) {
	callbackDeferred = callback;

  // simple example how to provide data from an array `items`:
  var start = opts.page * opts.pageSize;
  var end = start + opts.pageSize;
  callback(items.slice(start, end));
};

// when new items arrive, do
callbackDeferred(items.slice(start, end));
```

is there a better way of doing this? out of interest, how comes it doesn't return a `Promise`?
