### ISSUE TITLE
vertical scrollbar is added when horizontal scrollbar is used

### ISSUE THREAD

**Issue by MFJust** [vaadin/vaadin-grid#375]
When a horizontal scrollbar is used, it automatically adds a vertical scrollbar.
When only using a vertical scrollbar, it works correctly.

![scrollbars](https://cloud.githubusercontent.com/assets/11571737/15572215/73527908-233f-11e6-92f3-7f022aac2c81.png)

**Comment by Saulis** [comment]
Hi there!

Adding a horizontal scrollbar will take some of the vertical space from inside the scrollable area, so I'd say this is expected behaviour. 

When you say you're only using a vertical scrollbar and the horizontal scrollbar doesn't appear then, I'm guessing that you're using automatically determined column widths which will take the size of the vertical scrollbar into account.

Have you tried what happens if you increase the `height` of the grid with a few pixels?

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version (now in beta) doesn’t have a similar issue.
