### ISSUE TITLE
Row Details Generator is constantly attached and detached upon scroll, scrolling becomes laggy when row details is open

### ISSUE THREAD

**Issue by Hypnotik1** [vaadin/vaadin-grid#378]
I created a custom Polymer element to use as a row editor for Vaadin-Grid.  Every time I scroll Vaadin-Grid, even if by a few pixels, the entire row details generator element is run through an insertBefore call so that my custom element is detached and reattached to the DOM.  When I scroll through Vaadin-Grid, it becomes laggy because my custom element is constantly being attached and reattached (even if it is still in the viewport of the grid).

For testing, I used a non Polymer row-editor to see if it would lag as well upon scrolling.  It took 250 <input> elements for it to lag the same as my custom element.

Is this a known issue?

**Comment by Saulis** [comment]
Hi there!

This is actually by design. Due to how the scrolling works, elements like `<tr>` are being re-used.
While the row elements are being re-used, some of them outside viewport will end up in being in the wrong order in the DOM. Now, accessibility tools like some screen readers assume that the `<tr>` elements in the DOM are always in the same order as the data they contain. 

So, `vaadin-grid` tries to keep the elements in the correct order by switching and sorting the elements around while scrolling. And of course when elements are being moved around even outside the viewport, all the rows will be affected.

I believe this behaviour is what's causing your component to attach and detach while scrolling.

To mitigate the lagginess, I'd suggest you try to make sure no heavy operations get executed on the attach or detach phases of your component.

**Comment by Hypnotik1** [comment]
@Saulis I understand, and thank you for your reply.  I can try to trim down on what I'm doing but there isn't much.  Polymer might just be a little too heavy-weight for something like this, but I'm not sure of that yet.  

As a possible alternative solution, albeit 'hacky', would it make sense to prevent vaadin-grid from scrolling while I'm using my row details generator?  I couldn't find a way to catch any kind of scrolling events from vaadin-grid because they seem to be consumed before I can catch them.

**Comment by Saulis** [comment]
Well.. you can prevent scrolling with:
```js
grid.addEventListener('wheel', function(e) {
  e.stopPropagation();
}, true);
```
__but__, it won't work with touch devices since they use different events for scrolling, so I can't say I'd recommend this approach :-)

Polymer shouldn't add much overhead for attaching so I'm quite confident you can mitigate the lagginess of the scroll by moving all possible execution from the attach/detach lifecycle callbacks to somewhere else.
