### ISSUE TITLE
Theming API

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#534]
Design and implement the necessary mixins for the grid.

**Comment by tomivirkki** [comment]
# Theming API proposal

The aim of the research was to come up with a minimal theming API for the `vaadin-grid` 2.0 that could still cover a lot of the common use-cases when it comes to implementing a custom design.

The proposal suggests an MVP approach; the theming API can be expanded on demand anytime but providing too rich set initially might be counter-productive in terms of long-term maintenance.

The prototype API was formed by trying out how the current `vaadin-grid` 2.0-pre2 version could be styled to match a specific custom design and then deriving any repetitive patterns/parts whose theming turned out to be unnecessarily verbose or parts that were impossible to theme without proper APIs and turning them into built-in style mixins.

Two additional custom designs were implemented with the initial API to see if it serves it's purpose/to find any lackings.

The source for the current theming API prototype is at [2.0-proto-styling](https://github.com/vaadin/vaadin-grid/tree/2.0-proto-styling) branch. The demos are at ../demo/styling.html


## Notes

- We should agree on the default look and feel of the `vaadin-grid` before proceeding with the implementation.
- For many cases where the proposed API isn't sufficient per se, a proper solution may be to define named wrapper elements in the column templates instead of expanding the theming API to suit a particular use-case. (See "Styling 3" demo in the prototype demos for example)
- Dependencies/related issues (in priority order):
  - [Map flex into CSS flex instead of just flex-grow](https://github.com/vaadin/vaadin-grid/issues/527)
  - All cells must have a cell-content wrapper even if they didn't have a template (prototype has an implementation, need a separate issue perhaps?)
  - [Fix style scope issues](https://github.com/vaadin/vaadin-grid/issues/538)
  - [Empty header/footer rows shouldn't be displayed](https://github.com/vaadin/vaadin-grid/issues/549)

## Open questions
- Should our mixins target the `<td>`/`<th>` elements or the "cell-content" wrappers (`<div>`) directly inside of them?
  - Targeting the wrappers (`<div>`) might be safer since they're sort of isolated units that don't affect the grid's flow in any way
  - If [#527](https://github.com/vaadin/vaadin-grid/issues/527) allows a developer to set flex-basis for columns we might bump into [IE11 issues](https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box) with flex-basis + custom padding/borders (if styles are applied directly to cell (`<td>`) elements).
  - If the mixins target the cells (`<td>`) directly, there will be a wrapper (`<div>`) (whose styles the developer can't affect) in between the styled element and the actual content.

## Proposed theming API

The prototype proposes the following set of style mixins as the MVP:

### `<vaadin-grid>`
#### `--vaadin-grid-cell`: applies to all the cells (excluding detailscell)
#### `--vaadin-grid-cell-last-frozen`: applies to the last frozen column cells
#### `--vaadin-grid-header-cell`: applies to header cells
#### `--vaadin-grid-footer-cell`: applies to footer cells
#### `--vaadin-grid-body-cell`: applies to body cells (excluding detailscell)
#### `--vaadin-grid-body-row-odd-cell`: applies to body cells on odd rows (excluding detailscell)
#### `--vaadin-grid-body-row-hover-cell`: applies to body cells on hovered row (only while not scrolling, excluding detailscell)
#### `--vaadin-grid-body-row-selected-cell`: applies to body cells on selected rows (excluding detailscell)
#### `--vaadin-grid-body-row-details-cell`: applies to detailscell
#### `--vaadin-grid-loading-body-cell`: applies to body cells while in loading state
#### `--vaadin-grid-loading-spinner`: applies to the loading spinner

### `<vaadin-grid-sorter>`
#### `--vaadin-grid-sorter-indicator`: applies to the sorter indicator (pseudo element)
#### `--vaadin-grid-sorter-order`: applies to the sorter order element

**Comment by samiheikki** [comment]
Excellent proposition 🌮

**Comment by manolo** [comment]
I feel like `--vaadin-grid-loading-body-cell` could be renamed to `--vaadin-grid-body-loading-cell` to be aligned with other body related mixins. Another option since the cell is going to be always in the body is to remove the `-body-` part and align with the other loading mixin.

I miss mixins for first frozen and middle frozen columns. Unless they can be handled someway else, I would target `--vaadin-grid-frozen-cell` `--vaadin-grid-frozen-cell-first` `--vaadin-grid-frozen-cell-last`

Otherwise it looks a very comprehensive API 👍

**Comment by bennypowers** [comment]
How can we style row detail contents?
Say I want to do row-details like

    <span class="row-details-heading">Details:</span>
    [[item.details]]

**Comment by jouni** [comment]
@bennypowers: those elements will be in the light DOM, so you can use regular CSS selectors (in the same scope as your grid) to target them.

**Comment by jouni** [comment]
About the discussion on Friday, about prefixing the mixins or not: I think we still want to keep these low level API’s prefixed, just to be on the safe side.

We can do less verbose mixins and custom properties on the next, higher theme abstraction layer.

But still, I have an open question about the naming of the mixins: should we use BEM style structure for these, to improve the legibility?

For example:
`--vaadin-grid__header__cell`
`--vaadin-grid__body-row--odd__cell`
`--vaadin-grid__body-row--selected__cell`

**Comment by tomivirkki** [comment]
This is a decision that affects all the Vaadin Core Elements IMO and could be considered for a common practice for CE2.

If we don't want to decide this now, I'd rather stick to the current naming conventions to keep the `vaadin-grid` theming API in line with the rest of the Vaadin Core Elements and change the APIs for all the elements simultaneously when/if the time comes.

**Comment by jouni** [comment]
Sure, all elements need to align eventually. 

If we postpone the decision now, we will have to do a grid 3.0 if we decide to change the naming, right?

I don’t see a problem having the naming different for our 2.0 elements. Context menu and split layout are a bit on the fence. I would change the naming for those before 1.0 betas of we change it for the grid.

**Comment by Saulis** [comment]
Just as a comment, we might anyways need to do a grid 3.0 depending if we release 2.0 using Polymer 1/hybrid/2

**Comment by jouni** [comment]
@Saulis true. I don’t think we have a consensus on this yet. What do you think, should 2.0 be a hybrid or P2-only element? P1-only seems a bit unnecessary, as we would probably do the hybrid version pretty soon anyways after it.

Personally, I’m up for a P2-only element, if the timelines match nicely with Polymer 2.0, meaning if Polymer 2.0 is released before we would be ready to release grid 2.0.

**Comment by jouni** [comment]
One more thing: I think we can move forward with the set of mixins proposed here, and think about the naming more closely during the implementation. Would that be okay?

**Comment by tomivirkki** [comment]
Thumbs up

**Comment by jouni** [comment]
> Thumbs up

You know, there’s a “reaction” for that in GitHub 😉

**Comment by tomivirkki** [comment]
Haha, sure 🙃

**Comment by bennypowers** [comment]
FWIW from a user's perspective I think a hybrid elem is the way to go. Users might be stuck with 1.0 elems from upstream, or could have other reasons to not want to upgrade just yet. Also, a well-written hybrid elem should be more-trivial to update to 2.0 with the (promised) automated tools `</my-two-cents>`

**Comment by jouni** [comment]
Thanks for the feedback @bennypowers!

### About hybrid and 2.0 elements

I was maybe going to propose we upgrade the current 1.x grid to be a hybrid element, so people can still continue using that in their old applications, as that seems like the most common scenario. I’m not expecting that many users to migrate from vaadin-grid 1.x to 2.0 at the same time as they migrate from Polymer 1.x to 2.0, as they would be more focused on just keeping the app functional without having to rethink a lot of the actual application code.

Once they would have a functional app running on top of Polymer 2.0, with hybrid elements, they would start looking for ways to upgrade the elements to 2.0-only elements. And there they would probably be more willing to make changes to the application code as well.

### BEM style naming

@bennypowers, would you be confused if you encountered BEM style mixin or custom property names in a Polymer element?

**Comment by bennypowers** [comment]
It's not what I would expect, since the convention that seems to have emerged is `--prefix-el-selector-sub-sub` as in `--paper-card-header-image-text`. That's not to say that people can't get used to it, but I would prefer not to have to remember "oh yeah, this is that namespace with the weird naming convention in their elems"

**Comment by jouni** [comment]
Right, thanks again @bennypowers. That’s basically my fear, that it might alienate some users. I think we probably want to stick with the less explicit current convention (single dashes) for these low level theme APIs. When we work on the higher level customizable theme, I think it will be safer to utilize BEM style naming there.

**Comment by Saulis** [comment]
As discussed in the grooming, we'll include unit tests per mixin.
