### ISSUE TITLE
 computed properties in rows

### ISSUE THREAD

**Issue by osvaldoM** [vaadin/vaadin-grid#651]
I need to use to use computed properties to convert some of the data i get from the server into another format. is there a way to acomplish something like ` item="compute(data.name)" `

**Comment by tomivirkki** [comment]
Hi @osvaldoM,

Are you using `<vaadin-grid>` 1 or 2?

In case you're using the version 2, you can define computed bindings right in the column templates for example like in the following snippet:

```
<template>
  [[_compute(item)]]
</template>

...


_compute: function(item) {
  return item.name;
}
```

Let me know if this answer was what you're looking for.

**Comment by osvaldoM** [comment]
hey @tomivirkki  , i'm currently using v1. since v2 is apparently under development, is there anyway to achieve this using v1 or should i use v2?

**Comment by tomivirkki** [comment]
V1 doesn't have similar template-based approach for the column cells that V2 does but instead this "cell renderer" concept, which can be hooked to any data programmatically.

Grid 2 is currently at alpha stage but we're hoping to reach beta really soon now. Sorting and filtering should work, are you sure you're using the latest version? Note: Built-in sorting/filtering only works with `items`, so if you're using `dataSource` you'll have to take care of filtering/sorting of the data yourself.

I strongly suggest continuing with V2, as it's going to be superior to V1 in pretty much everything and we're not that far from the first stable release anyway. Note: Since we're not at beta stage yet, API changes, while unlikely, are possible.

**Comment by osvaldoM** [comment]
thanks. @tomivirkki  i have managed to use the cell renderer to achieve it, however i'm having another problem described here #6? also.  the function .then() is not defined in v2? #654  i'm currently testing the two versions
