### ISSUE TITLE
Mouse Wheel Scrolling, inside a grid maximised to the full window size, seems to halt the scrolling just after it starts.

### ISSUE THREAD

**Issue by hegsie** [vaadin/vaadin-grid#702]
Additionally when the grid is mid way down the scrollbar the mouse wheel scrolling seems to just not work at all.

**Comment by tomivirkki** [comment]
Hi, @hegsie 

Which version of `<vaadin-grid>` are you using? Made a couple of tests with full window size grid in them. In both cases the wheel scrolling seems to be working fine.

`<vaadin-grid>` 1: http://output.jsbin.com/vubudugone
`<vaadin-grid>` 2: http://output.jsbin.com/bogaqajisi

Is it possible you'd create a similar jsbin example to demonstrate the issue?

**Comment by hegsie** [comment]
sorry struggled getting the jsbin working....
https://1drv.ms/u/s!AldX7w6WhgIRhtBhwARgtJU7S0sF3w

**Comment by tomivirkki** [comment]
Hi, looks like in this case the layout is causing the issue. You’ve set grid’s height to be 100% but the parent’s height isn’t determined. If you want the app to take full height of the window, you’ll first need to make html element 100% high:
```
html {
    height: 100%;
}
```

After that you should see that every ancestor element of grid has appropriate height so that finally telling grid to have 100% height of it’s parent element works as expected.

Dirtier solution would be to make the grid’s height to be 100% of the viewport height and subtract the header height from that: `height: calc(100vh - 64px);` but yeah..that’s not an elegant approach.

**Comment by hegsie** [comment]
hmm i've tried adding your solution and it doesn't actually resolve the issue. even setting the height of the children of the iron-pages along with the html height doens't seem to fix the scrolling.  I can see in chrome that the computed values for height and are set for the grid, is there nything else you added to get the scrolling working?

**Comment by tomivirkki** [comment]
Ok, so starting from the app you linked, here's what I did to fix the layout:

index.html
 - set `html` and `body` to have `height: 100%`

bigboy-online-app.html
 - Added missing imports (app-drawer-layout.html and app-header-layout.html)
 - The component was missing display property so made it `display: block` (in `:host {}`)
 - Made it have 100% height  (in `:host {}`)
 - Made `iron-pages` 100% high
 - Added `fullbleed` attribute to `app-drawer-layout`
 - Added `has-scrolling-region` attribute to `app-header-layout`

accounts-list.html
 - The component was missing display property so made it `display: block` (in `:host {}`)
 - Made it have 100% height  (in `:host {}`)
 - Made `vaadin-grid` have `overflow: hidden` (this shouldn't be needed, we'll fix this)

Let me know if this works for you :)

**Comment by rendomnet** [comment]
This method will use scroll inside vaadin-grid. But I want to use outside container scroller and maximize vaadin-grid inside this container.

**Comment by tomivirkki** [comment]
HI @rendomnet, 

The `<vaadin-grid>` is designed to be primarily a virtual scroller so that it automatically optimizes the count of actual DOM elements (rows) and recycles them on (internal) scroll.

Surely you can set its height to `auto` making it stretch depending on the count of rows like in the “Dynamic Height” example at https://cdn.vaadin.com/vaadin-grid/2.0.0-beta1/demo/data.html. As long as the number of rows stays in fair limits this is fine but mind that the performance of automatically stretching grid will slow down if the row count increases a lot since every new row adds a number of elements to the DOM.

**Comment by rendomnet** [comment]
But when I mouse scroll over such grid nothing happens. Scrolling is not working.

**Comment by tomivirkki** [comment]
If the scrolling issue occurs only with "wheel", then it's likely due to this https://github.com/vaadin/vaadin-grid/issues/820
