### ISSUE TITLE
Could helper elements be automatically loaded with imporHref?

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-grid#770]
For the features that currently require manual importing of helper elements – couldn't we help with that? When checking the local DOM, it would notice a `<vaadin-grid-selection-column>` and then do `importHref` programmatically for that. If none is encountered, no import would be done. 

One issue might be that builds would have trouble picking up those helper elements and include them in bundles..

**Comment by manolo** [comment]
@vaadin-marcus is it ok to you to include the `all-imports.html` introduced in https://github.com/vaadin/vaadin-grid/pull/829/files ? 
I think loading dynamically it's not such a good idea because when building with polymer-cli the helper files could be skip. So the app could work in dev mode but not in production mode.
