### ISSUE TITLE
Laggy Sort after expand and collapse details

### ISSUE THREAD

**Issue by diegocerdan** [vaadin/vaadin-grid#798]
After expanding and collapsing the details of a row, sorting columns becomes very slow and CPU goes to 100% for couple of seconds.

Here a video demostration: https://youtu.be/eBgpOLy2e_A

Interesting enough, if you only expand a column (but not collapse it again) the sorting works as expected. Something inside the collapse process leaves the element in a state that triggers the bug.

**Comment by diegocerdan** [comment]
Never mind, I trigger the bug myself by having `vaadin-grid { height: auto }` instead of `vaadin-grid { height: 100%; }`. My bad.

**Comment by diegocerdan** [comment]
Somehow the bug is still triggered:
http://4bc06277.ngrok.io/

**Comment by jouni** [comment]
Thanks for the live demo! I would suspect the sorting takes so long because you have all the data grid rows rendered in the DOM (173 rows). When sorted, all of those rows are re-rendered, causing the browser to do a lot of work – which is of course caused by vaadin-grid. But still, we can’t really do much since you’ve requested all of the rows to be rendered without lazy loading / virtual DOM.

So, I think this is related to #786, and disabling the vaadin-grid scroller.

**Comment by diegocerdan** [comment]
As you can see in the video and the live demo the bug only triggers if you expand row details and collapse it again. Without the bug the sorting takes place in less than a second. 

Actually sorting 173 elements has to be almost instant (easy computation) and the expensive part as you said is the re-render of the whole structure that, without the bug, takes around a second.

**Comment by jouni** [comment]
Ah, right, sorry for not taking a look at the video! I didn’t realize you didn’t even have the details visible, it’s enough that you just once opened and closed the details, and then sorting becomes laggy.

And yeah, meant that it takes long to re-render all the rows after sorting. Sorting 173 (or even thousands) of items in an array basically takes no time compared to the rendering.

**Comment by tomivirkki** [comment]
With the latest grid, detail cells are pre-rendered on each row so this shouldn't be an issue anymore. Reopen if still relevant.
