### ISSUE TITLE
Individual Row height depending on their content

### ISSUE THREAD

**Issue by rendomnet** [vaadin/vaadin-grid#836]
Can rows have their individual height depending of their content of this rows?
For example 
first row is 48px height 
second is 243px height 
third is 100px height?

**Comment by jouni** [comment]
In version 2.0 yes. In 1.2, no.

**Comment by rendomnet** [comment]
I'm asking about version 2.0.

**Comment by jouni** [comment]
Great! So in that case, it works out of the box. See the first example here: https://cdn.vaadin.com/vaadin-grid/2.0.0-beta2/demo/

**Comment by rendomnet** [comment]
But every row in that example and in my porject have the same height. They dont have individual heights. https://ibb.co/bW5PgF

**Comment by jouni** [comment]
Why does it show in your screenshot that the Address column has more content than it should? Have you edited that yourself, perhaps using the browser inspector? If yes, then that will not work as expected. The cell contents have to come from the data source when the row is rendered so that the grid can measure it correctly. Changing the content afterwards requires you to inform the grid about content updates so it knows to re-render the rows.

**Comment by rendomnet** [comment]
But the same thing happens in my project with preexisiting data.

**Comment by jouni** [comment]
Then it would help to see some code so we might be able to reproduce the issue. Would you be able to create a jsbin/jsfiddle?
