### ISSUE TITLE
Are there any event we can capture from gird?

### ISSUE THREAD

**Issue by hzmnet** [vaadin/vaadin-grid#857]
Are there any event we can capture from gird?

**Comment by Saulis** [comment]
Hi there @hzmnet !

If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then please either ask the question on our [Gitter chat](https://gitter.im/vaadin/vaadin-core-elements/) or submit it to [StackOverflow](http://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the `vaadin` tag to the question. 

Thanks!
