### ISSUE TITLE
event "selected-items-changed" will happen 2 times when select 1 item.

### ISSUE THREAD

**Issue by hzmnet** [vaadin/vaadin-grid#859]
event "selected-items-changed" will happen 2 times when select 1 item when there are 2 items

**Comment by Saulis** [comment]
Hi @hzmnet!

`selected-items-changed` is a Polymer change notification event (as all `-changed` events we fire) and by design, for arrays, there are two notification events when adding or removing items. One for notifying `selectedItems.length` has changed and another for `selectedItems.splices`. 

You can see the event path and detail values are different for these events.
