### ISSUE TITLE
double-click on row

### ISSUE THREAD

**Issue by nicolasr75** [vaadin/vaadin-grid#901]
I would like to handle a double-click on a row to show a dialog to edit the data.
I followed issue #324 and put a double-click handler on the containing div.
The problem is that double-clicking on a not previously selected row shortly selects the row and deselects it right after such that in my handler the `activeItem` is null.
If I select the row via a single click before double-clicking it, then `activeItem` references the item in the handler.

Is that the desired behavior or am I misunderstanding something?

**Comment by Saulis** [comment]
Hi there!

If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then please either ask the question on our [Gitter](https://gitter.im/vaadin/vaadin-core-elements/) or submit it to [StackOverflow](http://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the `vaadin` tag to the question. 

Regarding the `activeItem` behavior, what you've described – sounds to me like it works like intended.

The container trick mentioned in #324 looks like this: 
```html
<vaadin-grid-column>
  <template class="header">First Name</template>
  <template>
    <div on-dblclick="_edit">[[item.firstName]]</div>
  </template>
</vaadin-grid-column>
```

the idea here is to use `event.model.item` to access the clicked item in `_edit` function instead of using `activeItem`.

Here's a live example of that: https://jsbin.com/moyexek/edit?html,console,output

I'm going to close this ticket now, but if you have further questions about this, please join our chat room in [Gitter](https://gitter.im/vaadin/vaadin-core-elements/), we're very happy to help you there.

Thanks!

**Comment by nicolasr75** [comment]
Hello Saulis, thanks for your help and the jsbin. I will take your hint seriously to post "how-to" questions to Gitter or SO in the future. In this case, however, I would like to more clearly explain the problem shortly because I don't consider it expected behavior, at least not to me.
I forgot to mention one important detail: in my application I color the active row. Add this to your `my-app` element in the jsbin:

```
<style>
	:host > * {
		--vaadin-grid-body-row-active-cell: {
			background-color: orange;
		};
	}
</style>
```
When you click a row, it becomes orange, when you click it again, the color is normal again. Fine. But when I double-click the cell, I would assume the row to stay active and that should be indicated by the orange color. I guess no user would double-click a row to unselect (deactivate) it! On the contrary, I want to do something with the double-clicked row, for example edit it in a dialog. The row should visually stay selected (active) during the entire operation and especially when I close the dialog.
You may have a different opinion on this, fair enough, I just wanted to clarify my actual problem.

**Comment by jouni** [comment]
I agree with @nicolasr75. I didn’t spend a lot of time thinking about it, but initially it seems logical that double click would keep the active state. 

One more question, though, regarding the exact behvior: when double clicking an already active row, does the row still stay active, or does it become inactive?

I assume there might be situations for both cases. I’m just trying to figure out how this works technically. The first idea I had was to “debounce” the activation so that we only change the activation state once within a certain time limit (a bit longer than the usual double click interval). But that means an active row will be deactivated when double clicked.

**Comment by nicolasr75** [comment]
Hello @jouni, just some random thoughts from my side:
two other popular grids seem to have a different default behavior. Examples here:

http://demos.telerik.com/kendo-ui/grid/selection
https://www.ag-grid.com/javascript-grid-selection/?framework=all#gsc.tab=0

They don't unselect (deactivate) the active item even on a single click. I guess that would then avoid a special handling for the double-click. On the other hand I definitely have use cases with multiple selection where I would like to deactivate items by single-clicking on them. Desktop file explorers in list mode seem to allow this by single-clicking selected items in combination with the Ctrl-key.

In another application with a grid in multiselect mode I put deactivation by single-click explicitly on top of the default behavior with my own code because the default behavior of the grid was again to not deactivate by single-click.

**Comment by Saulis** [comment]
@nicolasr75 I think I understand your use case – but I don't know if we're able to make that as a default behavior since, like Jouni pointed out there are some open questions about how active item should behave.

Here's an example how you can add your own customized double-click behavior: https://jsbin.com/quzoyan/edit?html,output

However, what I think you are actually after is having a customized single selection instead of using the `activeItem`: https://jsbin.com/piroja/edit?html,output

**Comment by nicolasr75** [comment]
@Saulis thanks for the new examples. The first one unfortunately doesn't work when the double-clicked item was already the active one - it gets deactivated. The second one is indeed a solution to my special case. Only drawback is that I would have to give an ID to all the grids in my app and write an `on-active-item-change` handler for each of them. So, if I had a chance to vote, I would vote for a default behavior where a click does not deactivate the active item ;-) At least that seems to be the default for the other grids that I linked to. Thanks to both of you for your time!

**Comment by sickinga** [comment]
i found a way to double click on rows, the only disadvantage is that you can not deactivate the item but besides that it works fine for me:
`      _activeItemChanged(item) {
        if(item != null) {
        this.$.grid.selectedItems = [item];
        }
        this._doubleTap(this.$.grid.selectedItems);
      }

      _doubleTap(item) {
        if(Array.isArray(item)) {
          item=item[0];
        }
        if(item != null) {
          if (item.tap == true)
            //code after a double tap
          item.tap = true;
          setTimeout(()=>{item.tap = false}, 500);
        }
      }`
