### ISSUE TITLE
Vaadin datepicker hidden inside vaadin grid.

### ISSUE THREAD

**Issue by rajesh-sharma-0490** [vaadin/vaadin-grid#914]
HI,
    While trying to embed a vaadin datepicker(2.0.0-alpha1) inside of vaadin grid(3.0.0-beta1) cell, the datepicker dialog seems to hide behind the grid. Updating the z-index doesn't seem to work. Any recommendation for the same?

**Comment by jper2** [comment]
Hi, I'm having same problema. Did you found any sulotion or workaround ?

**Comment by tomivirkki** [comment]
This will get fixed in https://github.com/vaadin/vaadin-date-picker/issues/465

**Comment by jper2** [comment]
Thanks for the quik reply.

I Added the <vaadin-date-picker-overlay> but ist’s empty. Can’t find na exemple with it. I’m newbie on this. Can you point me a direction or a simple sample?

Here’s the grid column definition i’m using:

<vaadin-grid-column width="150px">
                <template class="header">
                    <vaadin-grid-sorter path="updateDate">Update date</vaadin-grid-sorter>
                    <vaadin-grid-filter path="updateDate" />
                </template>
                <template>
                    <template is="dom-if" if="{{ item.selected }}">
                        <vaadin-text-field value="{{item.updateDate}}"> </vaadin-text-field>
                        <vaadin-date-picker-overlay value="{{item.updateDate}}">
                        </vaadin-date-picker-overlay>
                        <vaadin-date-picker value="{{item.updateDate}}"></vaadin-date-picker>
                    </template>
                    <template is="dom-if" if="{{ !item.selected }}">
                        {{item.updateDate}}
                    </template>
                </template>
            </vaadin-grid-column>


[cid:image001.png@01D36215.8A02A220]

Using the vaadin-date-picker it hides the date picker contente for selection:
[cid:image003.png@01D36216.4BFD7260]

Best regards,
João Pereira

De: Tomi Virkki [mailto:notifications@github.com]
Enviada: 20 de novembro de 2017 14:49
Para: vaadin/vaadin-grid <vaadin-grid@noreply.github.com>
Cc: João Pereira <jpereira@hydra.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [vaadin/vaadin-grid] Vaadin datepicker hidden inside vaadin grid. (#914)


This will get fixed in vaadin/vaadin-date-picker#465<https://github.com/vaadin/vaadin-date-picker/issues/465>

**Comment by tomivirkki** [comment]
https://github.com/vaadin/vaadin-date-picker/issues/465 is currently in progress. We're aiming to get an alpha out by the end of next week.

**Comment by web-padawan** [comment]
The fix mentioned above was released in [v3.0.0-alpha1](https://github.com/vaadin/vaadin-date-picker/releases/tag/v3.0.0-alpha1) release of the `vaadin-date-picker`, therefore I am closing this issue.
