### ISSUE TITLE
use on mobile devices responseWidth

### ISSUE THREAD

**Issue by esd100** [vaadin/vaadin-grid#919]
Is there any documentation on how to style or customize Vaadin-grid for different display sizes, such as on mobile devices by using a responseWidth property to the desired breakpoint resolution?

**Comment by jouni** [comment]
Here’s one example using iron-media-query: https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-grid/demo/columns.html#hiding-columns

**Comment by jouni** [comment]
Also, this seems more like a question than an issue (bug report or enhancement/feature request), which are usually better served in our Gitter chat: https://gitter.im/vaadin/vaadin-core-elements

Another option for questions is our forum on vaadin.com or stackoverflow

If you can reformulate this issue to a clearer description with a use case example, it would ve great. Otherwise I think we will close it and move the discussion to the chat.

**Comment by tomivirkki** [comment]
Closing as inactive.
