### ISSUE TITLE
expand to fill parent but not lose scrolling behavior?

### ISSUE THREAD

**Issue by alrossi** [vaadin/vaadin-grid#925]
Hello,

I have posted this question on the forum, but am unsure whether this is actually a problem with the component features, or whether I just do not understand how to make this behavior occur, since no one has replied so far.

https://vaadin.com/forum/#!/thread/16241278

(see my reply to Andrey)

This concerns version 2.0.3.

Essentially, what I am looking for is to be able to expand the height of the table to fill up the space allotted to its parent, but not lose the vertical and horizontal scrolling on the table itself.

Setting the grid height to auto or even to some specific value removes the vertical scrolling.   To get scrolling you need to set the overflow of the parent.  But in that case, the table headers no longer stay fixed at the top, but scroll away with the rest of the table; and, if you have a horizontal scroll bar on the table, you cannot see it unless you scroll completely down to the bottom.   

Leaving the height attribute unset on the table of course preserves the correct scrolling behavior, but then the table height is constrained to the equivalent of about 10 rows plus headers.

I have spent hours fooling around trying to find a solution to this problem.   I would really like to know if it is solvable.   It would be too bad if it cannot be solved, since vaadin-grid otherwise is extremely useful and fits the design of multiple pages for the frontend of the project I am working on.

(in the attached example, I have commented out the height on the grid and overflow on its parent; uncommenting should demonstrate the problem)

[test-page.txt](https://github.com/vaadin/vaadin-grid/files/1135514/test-page.txt)

**Comment by platosha** [comment]
It seems that the problem you experience is not specific to `<vaadin-grid>`, but rather a general CSS thing. Resizing elements to fill the viewport correctly is sometimes tricky to figure out.

Making `<vaadin-grid>` to fill the height is not different from resizing any other block element. There are several ways of achieving this, including: viewport height CSS units, percentage height, flexbox layout, etc. It’s up to developers to choose and apply the appropriate technique.

Looking at the given code, I think I can guess what was causing the difficulties in this case. The hierarchy is:

```
<test-page>
  ::shadow-root
    <iron-pages>
      <div>
        <vaadin-grid>
```

`<test-page>` and `<iron-pages>` do fill the viewport height. But there is also the `<div>` inside `<iron-pages>`, which is missing height. This prevents `vaadin-grid { height: 100%; }` from filling the viewport height for the grid, this is due to how CSS percentage height works. If you would have `height: 100%;` for both the div and the grid, it should work.

`vaadin-grid { height: auto; }` does not resize the grid to fill the parent height. This is also a standard CSS behavior, `height: auto;` means take height of the contents, not the height of the parent.

What I would suggest for your layout is to use `height: 100vh;` on the `<test-page>` hosting element, then apply flexbox layouts and `flex: 1;` inside to expand the elements that should fill the height, including the grid and all the parents. Please take a look here: http://jsbin.com/sekulugoke/edit?html,output.

**Comment by alrossi** [comment]
Thank you so much, Anton.  I will try out your suggestions.  I suspected it might actually be something subtle with the css, but I am still getting a feel for these subtleties.
