### ISSUE TITLE
Filtering while using pagination

### ISSUE THREAD

**Issue by abusham** [vaadin/vaadin-grid#929]
Hello All ,
First thanks for the awesome component.

I have a problem with filtration while having the pagination component, The pagination chunks the items into the specified page size, and when you filter , the behavior is that it looks into the items array , in this case it only finds the items on the current page , and not the full original array before pagination (expected behavior). 

Help please.

**Comment by platosha** [comment]
@abusham I would suggest to switch from using the array `items` to the `dataProvider`.

The `dataProvider` is, basically, a function callback that the grid uses to fetch the items. The filters and the sorting order information is provided in the callback arguments, so that in the callback you can implement filtering of the full dataset. Please see [`dataProvider` live demo](https://cdn.vaadin.com/vaadin-grid/3.0.0-beta1/demo/data.html#assigning-remote-function-data) and [API documentation](https://cdn.vaadin.com/vaadin-grid/3.0.0-beta1/#vaadin-grid:property-dataProvider).

Note that the `dataProvider` is made with remote API support in mind. If you have the full dataset as a JS array in the browser already, it might make sense to not use pagination altogether. The grid uses virtual scrolling inside, it does not render all the items but only a visible subset, there is no need to paginate the items to avoid slow renering.

**Comment by platosha** [comment]
Closing as this is a usage question, not an issue in the element.

**Comment by abusham** [comment]
@platosha Thank you
