### ISSUE TITLE
Select items in current page

### ISSUE THREAD

**Issue by madiganz** [vaadin/vaadin-grid#992]
I am using the data provider, but I would like the select all to only select the items on the current page. Is there a way to query just these items? I have access to items via _cache, but the items array is always empty. Also not sure how to determine what page is currently being viewed.

**Comment by manolo** [comment]
we don't have that feature, but im my opinion, selecting only items in the viewport might be a bad UX, because any accidental movement in the scroll would confuse the user.
I'd rather show to my users a paginated solution instead, where you can slice your data based on any criteria.  You can see a pagination demo here https://cdn.vaadin.com/vaadin-grid/2.0.3/demo/pagination.html

**Comment by madiganz** [comment]
I agree with you. This feature does not really make sense with virtual paging using the data provider. If this is desired, then you are correct that the actual paging solution is better.
